# REST API

## Get All Profiles
GET http://localhost:3000/profile

## Create New Profiles
### Curl -X POST http://localhost:3000/profile
POST http://localhost:3000/profile
Content-Type: application/json

{
    "username": "demo",
    "password": "1234",
    "mobile": "1234567890",
    "cardId": "1234567890000"


}